/**
 * Client labels for Select client(s) — mirrors AllowedClients.RAW order.
 * Used as checkbox options in the agent control UI.
 */
window.AGENT_CLIENTS = [
	"SSM Clay City Reports",
	"Mitchell Reports",
	"Missing Union ED Reports",
	"ED Appling Healthcare ER (SLMDAHER)",
	"Urgent Care Center at Venice (GPNL-S206)",
  "CAPE FEAR VALLEY MEDICAL CENTER",
  "Sarasota Memorial Hosp Veni... (GPNL-S103)",
  "Sarasota Memorial Hospital",
  "Sarasota Memorial Hospital 23 (GPNL-S101)",
  "3Madison County Memorial Rep...",
  "Carson Tahoe RMC Reports",
  "Missing Carson Tahoe RMC Re...",
  "Carson Tahoe Regional",
  "Carson Tahoe Regional Med C... (CTEP-11)",
  "Minden Emergent Care",
  "Besty Johnson Hospital",
  "Betsy Johnson Hospital ED (CVF1BJH)",
  "BLADEN COUNTY HOSPITAL",
  "BLADEN COUNTY HOSPITAL (BCH23-CFV1)",
  "CAPE FEAR VALLEY HOKE HOSPITAL",
  "CAPE FEAR VALLEY HEALTHCARE... (CFV1CFHH)",
  "CAPE FEAR VALLEY MEDICAL CENTER",
  "CAPE FEAR VALLEY MEDICAL CE... (CFVNC1)",
  "Central Harnett Hospital",
  "Central Harnett Hospital ED (CVF1CHH)",
  "Missing Indiana Reports",
  "FRANCISCAN ALLIANCE INDIANAPOLIS",
  "Franciscan Alliance Indiana... (EPI1-101)",
  "FRANCISCAN ALLIANCE MOORESVILLE",
  "Franciscan Alliance Mooresv... (EPI1-103)",
  "SMH ER at Lakewood",
  "Sarasota Mem ER Lakewood Ra... (GPNL-S104)",
  "SMH North Port",
  "Sarasota Memorial Hosp N Po... (GPNL-S102)",
  "SMH Venice",
  "Comm Hosp East Reports",
  "Community Heart and Vascular",
  "Community Heart Vascular Hosp ER(COMHVHER)",
  "Community Hospital East",
  "Community Hospital East ER (COMHOPEER)",
  "Community Hospital North",
  "Community Hospital North ER (COMHOPNER)",
  "Community Hospital South",
  "Community Hospital South ER (COMHOPSER)",
  "Community Howard Regional Health",
  "Community Howard Regional H... (COMHRHER)",
  "Missing SSM Good Sam Reports",
  "Missing SSSM St Mary Reports",
  "SSM Good Sam Reports",
  "SSM St Mary Reports",
  "ANDERSON HOSPITAL",
  "Anderson Hospital ER (MEDS-102)",
  "CLAY COUNTY HOSPITAL",
  "Clay County Hospital ER (MEDS-114)",
  "COMMUNITY HOSPITAL OF STAUNTON",
  "Community Hospital of Staun... (MEDS-105)",
  "SPARTA COMMUNITY HOSPITAL",
  "Sparta Community Hospital ER (MEDS-117)",
  "SSM GOOD SAMARITAN",
  "SSM Good Samaritan ER (MEDS-111)",
  "SSM ST MARYS HOSPITAL",
  "SSM St Marys Hospital ER (MEDS-108)",
  "Beckley Reports",
  "Berrien Reports",
  "Brooks Reports",
  "Burke ED Reports",
  "Chatuge RNH reports",
  "Grady Reports",
  "Jefferson Reports",
  "Jenkins Reports",
  "Missing Bleckley ED Downtime",
  "Missing Burke Hosp Reports",
  "Missing Dodge ED Reports",
  "Missing Grady ED Reports",
  "Missing JeffDavis Reports",
  "Mitchell Reports",
  "Monroe ED Reports",
  "Screvin Reports",
  "Tattnall Reports",
  "Taylor ED Reports",
  "Union General Reports",
  "Washington CO Reports",
  "Wayne Memorial Reports",
  "Wills ED Reports",
  "Appling Healthcare ED",
  "ED Appling Healthcare ER (SLMDAHER)",
  "Bainbridge ED",
  "ED MEMORIAL HOSPITAL AND MA... (SLMDMHM23)",
  "BLECKLEY ED",
  "ED BLECKLEY MEMORIAL HOSPIT... (SLMDBBMH23)",
  "Brooks County Hospital ED",
  "ED BROOKS COUNTY HOSPITAL ED (SLMDBCHE23)",
  "Burke ED",
  "ED Burke Medical Center ER (SLMDBMC23)",
  "CLINCH ED",
  "ED CLINCH MEMORIAL HOSPITAL ER (SLMDCH23)",
  "DODGE COUNTY ED",
  "ED DODGE COUNTY HOSPITAL ER (SLMDDC23)",
  "Elbert ED",
  "ED ELBERT MEMORIAL HOSPITAL ED (ELBERTMH23)",
  "EVANS ED",
  "ED EVANS MEMORIAL HOSPITAL ER (SLMDEE23)",
  "HSP EVANS HOSPITAL 23 (SLMDEH23)",
  "Grady General Hospital ED",
  "ED GRADY GENERAL HOSPITAL ED (SLMDGGHE23)",
  "IRWIN COUNTY HOSPITAL ED (SLMDICHE23)",
  "JEFF DAVIS ED",
  "ED Jeff Davis Hospital ER (SLMDJDH23)",
  "Jefferson ED",
  "ED Jefferson Hospital ER (SLMDJH23)",
  "Jenkins Co ED",
  "ED JENKINS COUNTY HOSPITAL ED (SLMDJCHE23)",
  "LIBERTY REGIONAL ED",
  "ED LIBERTY EMERG MEDICAL SE... (SLMDLR23)",
  "Madison County Memorial",
  "DoNotUseXMadison County Mem... (SLMDMCM23)",
  "SMD EMS Madison ER (SLMDSMD23)",
  "Mitchell County ED",
  "ED MITCHELL COUNTY ED (SLMDMCE23)",
  "Monroe County ED",
  "Monroe County Hospital ER (SLMDMONH23)",
  "NORTHRIDGE MEDICAL CENTER ER (SLMDNRMC23)",
  "ED SCREVEN COUNTY HOSPITAL ED (SLMDSCHE23)",
  "Optim Medical Center Screven (SLMDOMCSER)",
  "ED CHATUGE REGIONAL HOSPITAL (SLMDCRH23)",
  "SOUTHLAND LAKELAND EMERGENCY MEDICAL SERVICES, LLC",
  "ED SGMC LANIER CAMPUS LAKEL... (SLMDSLCL23)",
  "SOUTHLAND NASHVILLE EMERGENCY SERVICES, LLC",
  "ED SGMC BERRIEN CAMPUS (SLMDSBC23)",
  "Southland Union",
  "ED UNION GENERAL HOSPITAL (SLMDUG23)",
  "Southland Wills",
  "ED WILLS MEMORIAL HOSPITAL (SLMDWMH23)",
  "STEPHENS ED",
  "STEPHENS COUNTY HOSPITAL ER (SLMDSC23)",
  "Tattnall ED",
  "ED TATTNALL ER (SLMDOPCT23)",
  "Taylor Regional ED",
  "ED TAYLOR REGIONAL HOSPITAL ED (SLMDTRHE23)",
  "Washington County Regional ED",
  "ED Washington Co Reg Medica... (SLMDEWCR23)",
  "Missing Uvalde Reports",
  "Val_Verde Missing Reports",
  "CHOSA STONE OAK",
  "CHOSA Stone Oak ED (VEA1-01)",
  "CHOSA WEST OVER HILLS",
  "CHOSA West Over Hills ED (VEA1-02)",
  "CONNALLY MEMORIAL",
  "Connally Memorial ED (VEA1-10)",
  "CSRH NEW BRAUNFELS",
  "Christus SR Hosp New Braunf... (VEA1-06)",
  "CSRH WESTOVER HILLS",
  "Christus SR Hosp Westover H... (VEA1-08)",
  "CSRH ALAMO HEIGHTS",
  "Christus SR Hosp Alamo Heig... (VEA1-03)",
  "CSRH ALON",
  "Christus SR Hospital Alon ED (VEA1-04)",
  "CSRH CREEKSIDE",
  "Christus SR Hosp Creekside ED (VEA1-05)",
  "CSRH MEDICAL CENTER",
  "Christus SR Hosp Med Center ED (VEA1-09)",
  "CSRH SAN MARCOS",
  "Christus SR Hosp San Marcos ED (VEA1-07)",
  "DETAR HOSPITAL NORTH",
  "DeTar Hospital North ED (VEA1-13)",
  "DETAR NAVARRO",
  "DeTar Navarro ED (VEA1-14)",
  "DETAR NAVARRO CHEST PAIN UNIT",
  "MATAGORDA REGIONAL MED CTR",
  "Matagorda Regional Medical ... (VEA1-17)",
  "MEDINA REGIONAL HOSPITAL",
  "Medina Regional Hospital ED (VEA1-18)",
  "UVALDE MEMORIAL",
  "Uvalde Memorial ED (VEA1-20)",
  "Uvalde Memorial HM21 (VEA1-19)",
  "VAL VERDE REGIONAL MED CTR",
  "Val Verde Regional Medical ... (VEA1-22)",
  "YOAKUM COMMUNITY HOSPITAL",
  "Yoakum Community Hospital ED (VEA1-28)"
];
