/**
 * Client labels for Select client(s) — mirrors AllowedClients.RAW order.
 * Used as checkbox options in the agent control UI.
 */
window.AGENT_CLIENTS = [
	"Mitchell Reports",
	"Missing Union ED Reports",
	"ED Appling Healthcare ER (SLMDAHER)",
	"Urgent Care Center at Venice (GPNL-S206)",
  "CAPE FEAR VALLEY MEDICAL CENTER",
  "4Sarasota Memorial Hosp Veni... (GPNL-S103)",
  "Sarasota Memorial Hospital",
  "5Sarasota Memorial Hospital 23 (GPNL-S101)",
  "63Madison County Memorial Rep...",
  "54Carson Tahoe RMC Reports",
  "4Missing Carson Tahoe RMC Re...",
  "Carson Tahoe Regional",
  "0Carson Tahoe Regional Med C... (CTEP-11)",
  "Minden Emergent Care",
  "Besty Johnson Hospital",
  "0Betsy Johnson Hospital ED (CVF1BJH)",
  "BLADEN COUNTY HOSPITAL",
  "0BLADEN COUNTY HOSPITAL (BCH23-CFV1)",
  "CAPE FEAR VALLEY HOKE HOSPITAL",
  "0CAPE FEAR VALLEY HEALTHCARE... (CFV1CFHH)",
  "CAPE FEAR VALLEY MEDICAL CENTER",
  "104CAPE FEAR VALLEY MEDICAL CE... (CFVNC1)",
  "Central Harnett Hospital",
  "1Central Harnett Hospital ED (CVF1CHH)",
  "1Missing Indiana Reports",
  "FRANCISCAN ALLIANCE INDIANAPOLIS",
  "0Franciscan Alliance Indiana... (EPI1-101)",
  "FRANCISCAN ALLIANCE MOORESVILLE",
  "0Franciscan Alliance Mooresv... (EPI1-103)",
  "SMH ER at Lakewood",
  "1Sarasota Mem ER Lakewood Ra... (GPNL-S104)",
  "SMH North Port",
  "0Sarasota Memorial Hosp N Po... (GPNL-S102)",
  "SMH Venice",
  "13Comm Hosp East Reports",
  "Community Heart and Vascular",
  "0Community Heart Vascular Hosp ER(COMHVHER)",
  "Community Hospital East",
  "0Community Hospital East ER (COMHOPEER)",
  "Community Hospital North",
  "0Community Hospital North ER (COMHOPNER)",
  "Community Hospital South",
  "0Community Hospital South ER (COMHOPSER)",
  "Community Howard Regional Health",
  "0Community Howard Regional H... (COMHRHER)",
  "11Missing SSM Good Sam Reports",
  "2Missing SSSM St Mary Reports",
  "7SSM Good Sam Reports",
  "63SSM St Mary Reports",
  "ANDERSON HOSPITAL",
  "66Anderson Hospital ER (MEDS-102)",
  "CLAY COUNTY HOSPITAL",
  "0Clay County Hospital ER (MEDS-114)",
  "COMMUNITY HOSPITAL OF STAUNTON",
  "21Community Hospital of Staun... (MEDS-105)",
  "SPARTA COMMUNITY HOSPITAL",
  "10Sparta Community Hospital ER (MEDS-117)",
  "SSM GOOD SAMARITAN",
  "0SSM Good Samaritan ER (MEDS-111)",
  "SSM ST MARYS HOSPITAL",
  "0SSM St Marys Hospital ER (MEDS-108)",
  "21Beckley Reports",
  "8Berrien Reports",
  "16Brooks Reports",
  "2Burke ED Reports",
  "7Chatuge RNH reports",
  "26Grady Reports",
  "3Jefferson Reports",
  "8Jenkins Reports",
  "19Missing Bleckley ED Downtime",
  "3Missing Burke Hosp Reports",
  "3Missing Dodge ED Reports",
  "6Missing Grady ED Reports",
  "1Missing JeffDavis Reports",
  "23Mitchell Reports",
  "34Monroe ED Reports",
  "15Screvin Reports",
  "20Tattnall Reports",
  "38Taylor ED Reports",
  "1Union General Reports",
  "8Washington CO Reports",
  "57Wayne Memorial Reports",
  "149Wills ED Reports",
  "Appling Healthcare ED",
  "0ED Appling Healthcare ER (SLMDAHER)",
  "Bainbridge ED",
  "137ED MEMORIAL HOSPITAL AND MA... (SLMDMHM23)",
  "BLECKLEY ED",
  "0ED BLECKLEY MEMORIAL HOSPIT... (SLMDBBMH23)",
  "Brooks County Hospital ED",
  "0ED BROOKS COUNTY HOSPITAL ED (SLMDBCHE23)",
  "Burke ED",
  "0ED Burke Medical Center ER (SLMDBMC23)",
  "CLINCH ED",
  "0ED CLINCH MEMORIAL HOSPITAL ER (SLMDCH23)",
  "DODGE COUNTY ED",
  "0ED DODGE COUNTY HOSPITAL ER (SLMDDC23)",
  "Elbert ED",
  "0ED ELBERT MEMORIAL HOSPITAL ED (ELBERTMH23)",
  "EVANS ED",
  "0ED EVANS MEMORIAL HOSPITAL ER (SLMDEE23)",
  "0HSP EVANS HOSPITAL 23 (SLMDEH23)",
  "Grady General Hospital ED",
  "0ED GRADY GENERAL HOSPITAL ED (SLMDGGHE23)",
  "0IRWIN COUNTY HOSPITAL ED (SLMDICHE23)",
  "JEFF DAVIS ED",
  "0ED Jeff Davis Hospital ER (SLMDJDH23)",
  "Jefferson ED",
  "0ED Jefferson Hospital ER (SLMDJH23)",
  "Jenkins Co ED",
  "0ED JENKINS COUNTY HOSPITAL ED (SLMDJCHE23)",
  "LIBERTY REGIONAL ED",
  "0ED LIBERTY EMERG MEDICAL SE... (SLMDLR23)",
  "Madison County Memorial",
  "0DoNotUseXMadison County Mem... (SLMDMCM23)",
  "0SMD EMS Madison ER (SLMDSMD23)",
  "Mitchell County ED",
  "0ED MITCHELL COUNTY ED (SLMDMCE23)",
  "Monroe County ED",
  "0Monroe County Hospital ER (SLMDMONH23)",
  "0NORTHRIDGE MEDICAL CENTER ER (SLMDNRMC23)",
  "dff",
  "0ED SCREVEN COUNTY HOSPITAL ED (SLMDSCHE23)",
  "0Optim Medical Center Screven (SLMDOMCSER)",
  "2ED CHATUGE REGIONAL HOSPITAL (SLMDCRH23)",
  "SOUTHLAND LAKELAND EMERGENCY MEDICAL SERVICES, LLC",
  "0ED SGMC LANIER CAMPUS LAKEL... (SLMDSLCL23)",
  "SOUTHLAND NASHVILLE EMERGENCY SERVICES, LLC",
  "0ED SGMC BERRIEN CAMPUS (SLMDSBC23)",
  "Southland Union",
  "17ED UNION GENERAL HOSPITAL (SLMDUG23)",
  "Southland Wills",
  "0ED WILLS MEMORIAL HOSPITAL (SLMDWMH23)",
  "STEPHENS ED",
  "0STEPHENS COUNTY HOSPITAL ER (SLMDSC23)",
  "Tattnall ED",
  "0ED TATTNALL ER (SLMDOPCT23)",
  "Taylor Regional ED",
  "0ED TAYLOR REGIONAL HOSPITAL ED (SLMDTRHE23)",
  "Washington County Regional ED",
  "0ED Washington Co Reg Medica... (SLMDEWCR23)",
  "1Missing Uvalde Reports",
  "6Val_Verde Missing Reports",
  "CHOSA STONE OAK",
  "0CHOSA Stone Oak ED (VEA1-01)",
  "CHOSA WEST OVER HILLS",
  "0CHOSA West Over Hills ED (VEA1-02)",
  "CONNALLY MEMORIAL",
  "1Connally Memorial ED (VEA1-10)",
  "CSRH NEW BRAUNFELS",
  "0Christus SR Hosp New Braunf... (VEA1-06)",
  "CSRH WESTOVER HILLS",
  "0Christus SR Hosp Westover H... (VEA1-08)",
  "CSRH ALAMO HEIGHTS",
  "0Christus SR Hosp Alamo Heig... (VEA1-03)",
  "CSRH ALON",
  "0Christus SR Hospital Alon ED (VEA1-04)",
  "CSRH CREEKSIDE",
  "0Christus SR Hosp Creekside ED (VEA1-05)",
  "CSRH MEDICAL CENTER",
  "0Christus SR Hosp Med Center ED (VEA1-09)",
  "CSRH SAN MARCOS",
  "0Christus SR Hosp San Marcos ED (VEA1-07)",
  "DETAR HOSPITAL NORTH",
  "0DeTar Hospital North ED (VEA1-13)",
  "DETAR NAVARRO",
  "0DeTar Navarro ED (VEA1-14)",
  "DETAR NAVARRO CHEST PAIN UNIT",
  "MATAGORDA REGIONAL MED CTR",
  "0Matagorda Regional Medical ... (VEA1-17)",
  "MEDINA REGIONAL HOSPITAL",
  "0Medina Regional Hospital ED (VEA1-18)",
  "UVALDE MEMORIAL",
  "1Uvalde Memorial ED (VEA1-20)",
  "0Uvalde Memorial HM21 (VEA1-19)",
  "VAL VERDE REGIONAL MED CTR",
  "0Val Verde Regional Medical ... (VEA1-22)",
  "YOAKUM COMMUNITY HOSPITAL",
  "0Yoakum Community Hospital ED (VEA1-28)"
];
